[package]
name = "camera2d_ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
math = { git = "https:/github.com/bowarc/crates", package = "math", features = [
  "ggez",
] }
